version: "3.4"

services:
  node:
    image: node:18.14.0-alpine3.17
    entrypoint: "/usr/local/bin/entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./:/usr/src/app:rw
